### ISSUE TITLE
"has a hidden authenticity token input" test possible issue

### ISSUE THREAD

**Issue by fidel-techprep** [appdev-projects/helper-methods-part-1-and-2#2]
Hello!

I've been encountering issues with the "has a hidden authenticity token input" test.

After refactoring the code of the `movies/new.html.erb` template to use the `form_with(@model: ...)` helper method, the test begins to fail. It appears the test cannot "see" the authenticity token in my form, even though the source code indicates it's present.

If I revert to the "old way" of doing things—manually including the hidden `<input>` tag in the form—the test passes without any issues.

I've attached screenshots of my code and the HTML source code generated for both the `form_with` version (which fails) and the manual hidden tag version (which passes).

Thank you,
Fidel

**Failing**
<img width="1140" alt="form_with_template_code" src="https://github.com/appdev-projects/helper-methods-part-1-and-2/assets/127764786/56d5e817-c7c8-4ccd-b5e1-16957ac637ca">
<img width="1161" alt="form_with_source_code" src="https://github.com/appdev-projects/helper-methods-part-1-and-2/assets/127764786/730661df-50f6-4620-9a89-a5d24e929757">

**Passing**
<img width="1207" alt="hidden_tag_template_code" src="https://github.com/appdev-projects/helper-methods-part-1-and-2/assets/127764786/e1a385e5-8ab1-4e46-b049-52907a31f4d8">
<img width="1207" alt="hidden_tag_source_code" src="https://github.com/appdev-projects/helper-methods-part-1-and-2/assets/127764786/be1cb08a-6b62-4132-85d8-4566eb1e5b9b">

**Comment by bpurinton** [comment]
Sorry about this issue @fidel-techprep. Can you please: Make a git commit and push the current failing code to GitHub, then send me the link to your repository? I can spin up a codespace with your current version of the code and try to resolve the issue there.

**Comment by fidel-techprep** [comment]
Thank you for the quick reply! I just added the `form_with` method and ran the test again to confirm it still fails. Here is the repository will all changes pushed: [Helper Methods 1 & 2](https://github.com/fidel-techprep/helper-methods-part-1-and-2).

Thank you!

**Comment by bpurinton** [comment]
I removed this test. You should be able to run `rake grade` now and it will pull down my updates to the specs...

TIL! I spent awhile trying to debug before using GP-TA; here's the abridged answer from the AI:

```
The issue here is that Rails 7 forms no longer automatically include a hidden authenticity token input. This is because Rails 7 by default uses a new feature called “Cookieless CSRF protection”, which eliminates the need for an authenticity token inside the form.

Your test is failing because it expects to find a hidden authenticity token input, which doesn’t exist in your form.
```

**Comment by fidel-techprep** [comment]
Thank you, Ben! All tests pass now. And I got to learn from your debugging process too 🙌. Have a great day!
