### ISSUE TITLE
Typos to be fixed

### ISSUE THREAD

**Issue by AnnaVi11arrea1** [appdev-projects/helper-methods-part-1-and-2#7]
![Screenshot 2024-10-10 at 2 34 26 PM](https://github.com/user-attachments/assets/e4e9fb66-f6ef-4dee-882e-63977ec59074)
![Screenshot 2024-10-10 at 2 34 40 PM](https://github.com/user-attachments/assets/50ced09f-0794-404f-bfa7-b2ef0e26c11d)
![Screenshot 2024-10-10 at 2 50 11 PM](https://github.com/user-attachments/assets/6a521bcd-f234-4c1a-a12d-cf1883691e80)

**Comment by AnnaVi11arrea1** [comment]
Typos highlighted in blue.

**Comment by bpurinton** [comment]
Thanks! Resolved.
